version: "3"

services:
  webman:
    build:
      context: .
      dockerfile: ./environments/docker.dev/Dockerfile
    ports:
      - "8787:8787"
    volumes:
      - .:/app
  # 使用容器内的 redis 的话，修改 env 下的 REDIS_HOST 为 redis
#  redis:
#    image: redis:alpine
#    #ports:
#    #    - "6379:6379"
#    volumes:
#      - ./runtime/redis-data:/data
