POST {{baseUrl}}/auth/login
Content-Type: application/json

{"username":"admin","password":"123456"}

###

GET {{baseUrl}}/info
Accept: application/json
X-Api-Key: {{apiKey}}

###

POST {{baseUrl}}/auth/logout
Content-Type: application/json
X-Api-Key: {{apiKey}}

###
